name: Print Text on Folder Change 
on:
  push:
    paths:
      - "scripts/**"   
jobs:
  print-text-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Messages
        run: |
          echo "âœ… Changes detected in scripts folder!"
          echo "ðŸš€ Triggered on PUSH event"
          echo "ðŸ§¾ Printing CICD Logs Done"
